// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block_Type int32

const (
	Block_NOT_SET     Block_Type = 0
	Block_BACKEND_API Block_Type = 1
	Block_STATIC_SITE Block_Type = 2
	Block_WEB_APP     Block_Type = 3
	Block_JAMSTACK    Block_Type = 4
	Block_JOB         Block_Type = 5
	Block_CRON_JOB    Block_Type = 6
	Block_WORKER      Block_Type = 7
	Block_CATALOG     Block_Type = 8
	Block_HELM        Block_Type = 9
)

var Block_Type_name = map[int32]string{
	0: "NOT_SET",
	1: "BACKEND_API",
	2: "STATIC_SITE",
	3: "WEB_APP",
	4: "JAMSTACK",
	5: "JOB",
	6: "CRON_JOB",
	7: "WORKER",
	8: "CATALOG",
	9: "HELM",
}

var Block_Type_value = map[string]int32{
	"NOT_SET":     0,
	"BACKEND_API": 1,
	"STATIC_SITE": 2,
	"WEB_APP":     3,
	"JAMSTACK":    4,
	"JOB":         5,
	"CRON_JOB":    6,
	"WORKER":      7,
	"CATALOG":     8,
	"HELM":        9,
}

func (x Block_Type) String() string {
	return proto.EnumName(Block_Type_name, int32(x))
}

func (Block_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2, 0}
}

type Release_Type int32

const (
	Release_NOT_SET  Release_Type = 0
	Release_DEPLOY   Release_Type = 1
	Release_UNDEPLOY Release_Type = 2
	Release_SUSPEND  Release_Type = 3
	Release_ROLLBACK Release_Type = 4
)

var Release_Type_name = map[int32]string{
	0: "NOT_SET",
	1: "DEPLOY",
	2: "UNDEPLOY",
	3: "SUSPEND",
	4: "ROLLBACK",
}

var Release_Type_value = map[string]int32{
	"NOT_SET":  0,
	"DEPLOY":   1,
	"UNDEPLOY": 2,
	"SUSPEND":  3,
	"ROLLBACK": 4,
}

func (x Release_Type) String() string {
	return proto.EnumName(Release_Type_name, int32(x))
}

func (Release_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4, 0}
}

type BuildConfig_Language int32

const (
	BuildConfig_NOT_SET    BuildConfig_Language = 0
	BuildConfig_DOCKERFILE BuildConfig_Language = 1
	BuildConfig_GOLANG     BuildConfig_Language = 2
	BuildConfig_NODEJS     BuildConfig_Language = 3
	BuildConfig_PYTHON     BuildConfig_Language = 4
	BuildConfig_JAVA       BuildConfig_Language = 5
	BuildConfig_RUBY       BuildConfig_Language = 6
	BuildConfig_PHP        BuildConfig_Language = 7
	BuildConfig_RUST       BuildConfig_Language = 8
	BuildConfig_ELIXIR     BuildConfig_Language = 9
)

var BuildConfig_Language_name = map[int32]string{
	0: "NOT_SET",
	1: "DOCKERFILE",
	2: "GOLANG",
	3: "NODEJS",
	4: "PYTHON",
	5: "JAVA",
	6: "RUBY",
	7: "PHP",
	8: "RUST",
	9: "ELIXIR",
}

var BuildConfig_Language_value = map[string]int32{
	"NOT_SET":    0,
	"DOCKERFILE": 1,
	"GOLANG":     2,
	"NODEJS":     3,
	"PYTHON":     4,
	"JAVA":       5,
	"RUBY":       6,
	"PHP":        7,
	"RUST":       8,
	"ELIXIR":     9,
}

func (x BuildConfig_Language) String() string {
	return proto.EnumName(BuildConfig_Language_name, int32(x))
}

func (BuildConfig_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5, 0}
}

type RunConfig_Protocol int32

const (
	RunConfig_NOT_SET RunConfig_Protocol = 0
	RunConfig_HTTP    RunConfig_Protocol = 1
	RunConfig_GRPC    RunConfig_Protocol = 2
)

var RunConfig_Protocol_name = map[int32]string{
	0: "NOT_SET",
	1: "HTTP",
	2: "GRPC",
}

var RunConfig_Protocol_value = map[string]int32{
	"NOT_SET": 0,
	"HTTP":    1,
	"GRPC":    2,
}

func (x RunConfig_Protocol) String() string {
	return proto.EnumName(RunConfig_Protocol_name, int32(x))
}

func (RunConfig_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{6, 0}
}

type Status_State int32

const (
	Status_NOT_SET       Status_State = 0
	Status_FAIL          Status_State = 1
	Status_SUCCESS       Status_State = 2
	Status_RUNNING       Status_State = 3
	Status_PENDING       Status_State = 4
	Status_ABORTED       Status_State = 5
	Status_REVIEW_DEPLOY Status_State = 6
)

var Status_State_name = map[int32]string{
	0: "NOT_SET",
	1: "FAIL",
	2: "SUCCESS",
	3: "RUNNING",
	4: "PENDING",
	5: "ABORTED",
	6: "REVIEW_DEPLOY",
}

var Status_State_value = map[string]int32{
	"NOT_SET":       0,
	"FAIL":          1,
	"SUCCESS":       2,
	"RUNNING":       3,
	"PENDING":       4,
	"ABORTED":       5,
	"REVIEW_DEPLOY": 6,
}

func (x Status_State) String() string {
	return proto.EnumName(Status_State_name, int32(x))
}

func (Status_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{11, 0}
}

type BuildStatus_State int32

const (
	BuildStatus_NOT_SET        BuildStatus_State = 0
	BuildStatus_UNKNOWN        BuildStatus_State = 1
	BuildStatus_QUEUED         BuildStatus_State = 2
	BuildStatus_WORKING        BuildStatus_State = 3
	BuildStatus_SUCCESS        BuildStatus_State = 4
	BuildStatus_FAILURE        BuildStatus_State = 5
	BuildStatus_INTERNAL_ERROR BuildStatus_State = 6
	BuildStatus_TIMEOUT        BuildStatus_State = 7
	BuildStatus_CANCELLED      BuildStatus_State = 8
	BuildStatus_EXPIRED        BuildStatus_State = 9
)

var BuildStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "UNKNOWN",
	2: "QUEUED",
	3: "WORKING",
	4: "SUCCESS",
	5: "FAILURE",
	6: "INTERNAL_ERROR",
	7: "TIMEOUT",
	8: "CANCELLED",
	9: "EXPIRED",
}

var BuildStatus_State_value = map[string]int32{
	"NOT_SET":        0,
	"UNKNOWN":        1,
	"QUEUED":         2,
	"WORKING":        3,
	"SUCCESS":        4,
	"FAILURE":        5,
	"INTERNAL_ERROR": 6,
	"TIMEOUT":        7,
	"CANCELLED":      8,
	"EXPIRED":        9,
}

func (x BuildStatus_State) String() string {
	return proto.EnumName(BuildStatus_State_name, int32(x))
}

func (BuildStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{13, 0}
}

type BlockStatus_State int32

const (
	BlockStatus_NOT_SET   BlockStatus_State = 0
	BlockStatus_HEALTHY   BlockStatus_State = 1
	BlockStatus_UNHEALTHY BlockStatus_State = 2
	BlockStatus_SUSPENDED BlockStatus_State = 3
	BlockStatus_SLEEPING  BlockStatus_State = 4
)

var BlockStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "HEALTHY",
	2: "UNHEALTHY",
	3: "SUSPENDED",
	4: "SLEEPING",
}

var BlockStatus_State_value = map[string]int32{
	"NOT_SET":   0,
	"HEALTHY":   1,
	"UNHEALTHY": 2,
	"SUSPENDED": 3,
	"SLEEPING":  4,
}

func (x BlockStatus_State) String() string {
	return proto.EnumName(BlockStatus_State_name, int32(x))
}

func (BlockStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{15, 0}
}

type BlockInstance_State int32

const (
	BlockInstance_NOT_SET    BlockInstance_State = 0
	BlockInstance_RUNNING    BlockInstance_State = 1
	BlockInstance_COMPLETED  BlockInstance_State = 2
	BlockInstance_ERROR      BlockInstance_State = 3
	BlockInstance_OOM_KILLED BlockInstance_State = 4
)

var BlockInstance_State_name = map[int32]string{
	0: "NOT_SET",
	1: "RUNNING",
	2: "COMPLETED",
	3: "ERROR",
	4: "OOM_KILLED",
}

var BlockInstance_State_value = map[string]int32{
	"NOT_SET":    0,
	"RUNNING":    1,
	"COMPLETED":  2,
	"ERROR":      3,
	"OOM_KILLED": 4,
}

func (x BlockInstance_State) String() string {
	return proto.EnumName(BlockInstance_State_name, int32(x))
}

func (BlockInstance_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{18, 0}
}

type JobStatus_State int32

const (
	JobStatus_NOT_SET    JobStatus_State = 0
	JobStatus_PENDING    JobStatus_State = 1
	JobStatus_RUNNING    JobStatus_State = 2
	JobStatus_COMPLETED  JobStatus_State = 3
	JobStatus_DELETED    JobStatus_State = 4
	JobStatus_ERROR      JobStatus_State = 5
	JobStatus_OOM_KILLED JobStatus_State = 6
)

var JobStatus_State_name = map[int32]string{
	0: "NOT_SET",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETED",
	4: "DELETED",
	5: "ERROR",
	6: "OOM_KILLED",
}

var JobStatus_State_value = map[string]int32{
	"NOT_SET":    0,
	"PENDING":    1,
	"RUNNING":    2,
	"COMPLETED":  3,
	"DELETED":    4,
	"ERROR":      5,
	"OOM_KILLED": 6,
}

func (x JobStatus_State) String() string {
	return proto.EnumName(JobStatus_State_name, int32(x))
}

func (JobStatus_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{28, 0}
}

type Environment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Environments struct {
	Items                []*Environment `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Environments) Reset()         { *m = Environments{} }
func (m *Environments) String() string { return proto.CompactTextString(m) }
func (*Environments) ProtoMessage()    {}
func (*Environments) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *Environments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environments.Unmarshal(m, b)
}
func (m *Environments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environments.Marshal(b, m, deterministic)
}
func (m *Environments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environments.Merge(m, src)
}
func (m *Environments) XXX_Size() int {
	return xxx_messageInfo_Environments.Size(m)
}
func (m *Environments) XXX_DiscardUnknown() {
	xxx_messageInfo_Environments.DiscardUnknown(m)
}

var xxx_messageInfo_Environments proto.InternalMessageInfo

func (m *Environments) GetItems() []*Environment {
	if m != nil {
		return m.Items
	}
	return nil
}

type Block struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EnvId                string              `protobuf:"bytes,3,opt,name=envId,proto3" json:"envId,omitempty"`
	DisplayName          string              `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Releases             map[string]*Release `protobuf:"bytes,5,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomDomains        []string            `protobuf:"bytes,6,rep,name=customDomains,proto3" json:"customDomains,omitempty"`
	IsPublicURL          bool                `protobuf:"varint,7,opt,name=isPublicURL,proto3" json:"isPublicURL,omitempty"`
	ParentBlockName      string              `protobuf:"bytes,8,opt,name=parentBlockName,proto3" json:"parentBlockName,omitempty"`
	ParentBlockEnvId     string              `protobuf:"bytes,9,opt,name=parentBlockEnvId,proto3" json:"parentBlockEnvId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Block) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *Block) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Block) GetReleases() map[string]*Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *Block) GetCustomDomains() []string {
	if m != nil {
		return m.CustomDomains
	}
	return nil
}

func (m *Block) GetIsPublicURL() bool {
	if m != nil {
		return m.IsPublicURL
	}
	return false
}

func (m *Block) GetParentBlockName() string {
	if m != nil {
		return m.ParentBlockName
	}
	return ""
}

func (m *Block) GetParentBlockEnvId() string {
	if m != nil {
		return m.ParentBlockEnvId
	}
	return ""
}

type Blocks struct {
	Items                []*Block `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (m *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(m, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetItems() []*Block {
	if m != nil {
		return m.Items
	}
	return nil
}

type Release struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	BuildConfig          *BuildConfig         `protobuf:"bytes,3,opt,name=buildConfig,proto3" json:"buildConfig,omitempty"`
	RunConfig            *RunConfig           `protobuf:"bytes,4,opt,name=runConfig,proto3" json:"runConfig,omitempty"`
	Status               *Status              `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	EndedAt              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	Type                 Release_Type         `protobuf:"varint,8,opt,name=type,proto3,enum=Release_Type" json:"type,omitempty"`
	Tags                 []string             `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CommitSha            string               `protobuf:"bytes,10,opt,name=commitSha,proto3" json:"commitSha,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (m *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(m, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Release) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Release) GetBuildConfig() *BuildConfig {
	if m != nil {
		return m.BuildConfig
	}
	return nil
}

func (m *Release) GetRunConfig() *RunConfig {
	if m != nil {
		return m.RunConfig
	}
	return nil
}

func (m *Release) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Release) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *Release) GetEndedAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndedAt
	}
	return nil
}

func (m *Release) GetType() Release_Type {
	if m != nil {
		return m.Type
	}
	return Release_NOT_SET
}

func (m *Release) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Release) GetCommitSha() string {
	if m != nil {
		return m.CommitSha
	}
	return ""
}

type BuildConfig struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Language             BuildConfig_Language `protobuf:"varint,3,opt,name=language,proto3,enum=BuildConfig_Language" json:"language,omitempty"`
	LanguageVersion      string               `protobuf:"bytes,4,opt,name=languageVersion,proto3" json:"languageVersion,omitempty"`
	BuildCommand         string               `protobuf:"bytes,5,opt,name=buildCommand,proto3" json:"buildCommand,omitempty"`
	RunCommand           string               `protobuf:"bytes,6,opt,name=runCommand,proto3" json:"runCommand,omitempty"`
	PathToCode           string               `protobuf:"bytes,7,opt,name=pathToCode,proto3" json:"pathToCode,omitempty"`
	PathToStaticOutput   string               `protobuf:"bytes,11,opt,name=pathToStaticOutput,proto3" json:"pathToStaticOutput,omitempty"`
	DockerfileFileName   string               `protobuf:"bytes,8,opt,name=dockerfileFileName,proto3" json:"dockerfileFileName,omitempty"`
	BuildArgs            map[string]string    `protobuf:"bytes,9,rep,name=buildArgs,proto3" json:"buildArgs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Repository           *Repository          `protobuf:"bytes,10,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildConfig) Reset()         { *m = BuildConfig{} }
func (m *BuildConfig) String() string { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()    {}
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5}
}

func (m *BuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfig.Unmarshal(m, b)
}
func (m *BuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfig.Marshal(b, m, deterministic)
}
func (m *BuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfig.Merge(m, src)
}
func (m *BuildConfig) XXX_Size() int {
	return xxx_messageInfo_BuildConfig.Size(m)
}
func (m *BuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfig proto.InternalMessageInfo

func (m *BuildConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BuildConfig) GetLanguage() BuildConfig_Language {
	if m != nil {
		return m.Language
	}
	return BuildConfig_NOT_SET
}

func (m *BuildConfig) GetLanguageVersion() string {
	if m != nil {
		return m.LanguageVersion
	}
	return ""
}

func (m *BuildConfig) GetBuildCommand() string {
	if m != nil {
		return m.BuildCommand
	}
	return ""
}

func (m *BuildConfig) GetRunCommand() string {
	if m != nil {
		return m.RunCommand
	}
	return ""
}

func (m *BuildConfig) GetPathToCode() string {
	if m != nil {
		return m.PathToCode
	}
	return ""
}

func (m *BuildConfig) GetPathToStaticOutput() string {
	if m != nil {
		return m.PathToStaticOutput
	}
	return ""
}

func (m *BuildConfig) GetDockerfileFileName() string {
	if m != nil {
		return m.DockerfileFileName
	}
	return ""
}

func (m *BuildConfig) GetBuildArgs() map[string]string {
	if m != nil {
		return m.BuildArgs
	}
	return nil
}

func (m *BuildConfig) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type RunConfig struct {
	Type                    Block_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=Block_Type" json:"type,omitempty"`
	Port                    string             `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	AutoScaling             *AutoScaling       `protobuf:"bytes,3,opt,name=autoScaling,proto3" json:"autoScaling,omitempty"`
	EnvVars                 map[string]string  `protobuf:"bytes,4,rep,name=envVars,proto3" json:"envVars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources               *Resources         `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	TimeoutInSec            int32              `protobuf:"varint,6,opt,name=timeoutInSec,proto3" json:"timeoutInSec,omitempty"`
	JobSpec                 *JobSpec           `protobuf:"bytes,7,opt,name=jobSpec,proto3" json:"jobSpec,omitempty"`
	Host                    string             `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	CostOptimizationEnabled bool               `protobuf:"varint,9,opt,name=costOptimizationEnabled,proto3" json:"costOptimizationEnabled,omitempty"`
	SleepModeEnabled        bool               `protobuf:"varint,10,opt,name=sleepModeEnabled,proto3" json:"sleepModeEnabled,omitempty"`
	Protocol                RunConfig_Protocol `protobuf:"varint,11,opt,name=protocol,proto3,enum=RunConfig_Protocol" json:"protocol,omitempty"`
	SleepModeTTLSeconds     int32              `protobuf:"varint,12,opt,name=sleepModeTTLSeconds,proto3" json:"sleepModeTTLSeconds,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}           `json:"-"`
	XXX_unrecognized        []byte             `json:"-"`
	XXX_sizecache           int32              `json:"-"`
}

func (m *RunConfig) Reset()         { *m = RunConfig{} }
func (m *RunConfig) String() string { return proto.CompactTextString(m) }
func (*RunConfig) ProtoMessage()    {}
func (*RunConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{6}
}

func (m *RunConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunConfig.Unmarshal(m, b)
}
func (m *RunConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunConfig.Marshal(b, m, deterministic)
}
func (m *RunConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunConfig.Merge(m, src)
}
func (m *RunConfig) XXX_Size() int {
	return xxx_messageInfo_RunConfig.Size(m)
}
func (m *RunConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RunConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RunConfig proto.InternalMessageInfo

func (m *RunConfig) GetType() Block_Type {
	if m != nil {
		return m.Type
	}
	return Block_NOT_SET
}

func (m *RunConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *RunConfig) GetAutoScaling() *AutoScaling {
	if m != nil {
		return m.AutoScaling
	}
	return nil
}

func (m *RunConfig) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *RunConfig) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *RunConfig) GetTimeoutInSec() int32 {
	if m != nil {
		return m.TimeoutInSec
	}
	return 0
}

func (m *RunConfig) GetJobSpec() *JobSpec {
	if m != nil {
		return m.JobSpec
	}
	return nil
}

func (m *RunConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RunConfig) GetCostOptimizationEnabled() bool {
	if m != nil {
		return m.CostOptimizationEnabled
	}
	return false
}

func (m *RunConfig) GetSleepModeEnabled() bool {
	if m != nil {
		return m.SleepModeEnabled
	}
	return false
}

func (m *RunConfig) GetProtocol() RunConfig_Protocol {
	if m != nil {
		return m.Protocol
	}
	return RunConfig_NOT_SET
}

func (m *RunConfig) GetSleepModeTTLSeconds() int32 {
	if m != nil {
		return m.SleepModeTTLSeconds
	}
	return 0
}

type Repository struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	GithubInstallationId string   `protobuf:"bytes,4,opt,name=githubInstallationId,proto3" json:"githubInstallationId,omitempty"` // Deprecated: Do not use.
	GithubUserToken      string   `protobuf:"bytes,5,opt,name=githubUserToken,proto3" json:"githubUserToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{7}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Repository) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Repository) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

// Deprecated: Do not use.
func (m *Repository) GetGithubInstallationId() string {
	if m != nil {
		return m.GithubInstallationId
	}
	return ""
}

func (m *Repository) GetGithubUserToken() string {
	if m != nil {
		return m.GithubUserToken
	}
	return ""
}

type JobSpec struct {
	CronPattern          string   `protobuf:"bytes,1,opt,name=cronPattern,proto3" json:"cronPattern,omitempty"`
	TimeoutInSec         int32    `protobuf:"varint,2,opt,name=timeoutInSec,proto3" json:"timeoutInSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSpec) Reset()         { *m = JobSpec{} }
func (m *JobSpec) String() string { return proto.CompactTextString(m) }
func (*JobSpec) ProtoMessage()    {}
func (*JobSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{8}
}

func (m *JobSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSpec.Unmarshal(m, b)
}
func (m *JobSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSpec.Marshal(b, m, deterministic)
}
func (m *JobSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSpec.Merge(m, src)
}
func (m *JobSpec) XXX_Size() int {
	return xxx_messageInfo_JobSpec.Size(m)
}
func (m *JobSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSpec.DiscardUnknown(m)
}

var xxx_messageInfo_JobSpec proto.InternalMessageInfo

func (m *JobSpec) GetCronPattern() string {
	if m != nil {
		return m.CronPattern
	}
	return ""
}

func (m *JobSpec) GetTimeoutInSec() int32 {
	if m != nil {
		return m.TimeoutInSec
	}
	return 0
}

type AutoScaling struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	CpuPercent           int32    `protobuf:"varint,3,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoScaling) Reset()         { *m = AutoScaling{} }
func (m *AutoScaling) String() string { return proto.CompactTextString(m) }
func (*AutoScaling) ProtoMessage()    {}
func (*AutoScaling) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{9}
}

func (m *AutoScaling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoScaling.Unmarshal(m, b)
}
func (m *AutoScaling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoScaling.Marshal(b, m, deterministic)
}
func (m *AutoScaling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoScaling.Merge(m, src)
}
func (m *AutoScaling) XXX_Size() int {
	return xxx_messageInfo_AutoScaling.Size(m)
}
func (m *AutoScaling) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoScaling.DiscardUnknown(m)
}

var xxx_messageInfo_AutoScaling proto.InternalMessageInfo

func (m *AutoScaling) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *AutoScaling) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *AutoScaling) GetCpuPercent() int32 {
	if m != nil {
		return m.CpuPercent
	}
	return 0
}

type Resources struct {
	MemoryInMB           int32    `protobuf:"varint,1,opt,name=memoryInMB,proto3" json:"memoryInMB,omitempty"`
	CpuInCore            float32  `protobuf:"fixed32,2,opt,name=cpuInCore,proto3" json:"cpuInCore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{10}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetMemoryInMB() int32 {
	if m != nil {
		return m.MemoryInMB
	}
	return 0
}

func (m *Resources) GetCpuInCore() float32 {
	if m != nil {
		return m.CpuInCore
	}
	return 0
}

type Status struct {
	State                Status_State `protobuf:"varint,2,opt,name=state,proto3,enum=Status_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{11}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetState() Status_State {
	if m != nil {
		return m.State
	}
	return Status_NOT_SET
}

type ReleasesStatus struct {
	BlockName            string             `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string             `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	Releases             map[string]*Status `protobuf:"bytes,3,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReleasesStatus) Reset()         { *m = ReleasesStatus{} }
func (m *ReleasesStatus) String() string { return proto.CompactTextString(m) }
func (*ReleasesStatus) ProtoMessage()    {}
func (*ReleasesStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{12}
}

func (m *ReleasesStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasesStatus.Unmarshal(m, b)
}
func (m *ReleasesStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasesStatus.Marshal(b, m, deterministic)
}
func (m *ReleasesStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasesStatus.Merge(m, src)
}
func (m *ReleasesStatus) XXX_Size() int {
	return xxx_messageInfo_ReleasesStatus.Size(m)
}
func (m *ReleasesStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasesStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasesStatus proto.InternalMessageInfo

func (m *ReleasesStatus) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *ReleasesStatus) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *ReleasesStatus) GetReleases() map[string]*Status {
	if m != nil {
		return m.Releases
	}
	return nil
}

type BuildStatus struct {
	State                BuildStatus_State    `protobuf:"varint,1,opt,name=state,proto3,enum=BuildStatus_State" json:"state,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	FinishTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildStatus) Reset()         { *m = BuildStatus{} }
func (m *BuildStatus) String() string { return proto.CompactTextString(m) }
func (*BuildStatus) ProtoMessage()    {}
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{13}
}

func (m *BuildStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildStatus.Unmarshal(m, b)
}
func (m *BuildStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildStatus.Marshal(b, m, deterministic)
}
func (m *BuildStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildStatus.Merge(m, src)
}
func (m *BuildStatus) XXX_Size() int {
	return xxx_messageInfo_BuildStatus.Size(m)
}
func (m *BuildStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BuildStatus proto.InternalMessageInfo

func (m *BuildStatus) GetState() BuildStatus_State {
	if m != nil {
		return m.State
	}
	return BuildStatus_NOT_SET
}

func (m *BuildStatus) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *BuildStatus) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

type ConsoleLog struct {
	InstanceName         string   `protobuf:"bytes,1,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsoleLog) Reset()         { *m = ConsoleLog{} }
func (m *ConsoleLog) String() string { return proto.CompactTextString(m) }
func (*ConsoleLog) ProtoMessage()    {}
func (*ConsoleLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{14}
}

func (m *ConsoleLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsoleLog.Unmarshal(m, b)
}
func (m *ConsoleLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsoleLog.Marshal(b, m, deterministic)
}
func (m *ConsoleLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsoleLog.Merge(m, src)
}
func (m *ConsoleLog) XXX_Size() int {
	return xxx_messageInfo_ConsoleLog.Size(m)
}
func (m *ConsoleLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsoleLog.DiscardUnknown(m)
}

var xxx_messageInfo_ConsoleLog proto.InternalMessageInfo

func (m *ConsoleLog) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *ConsoleLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockStatus struct {
	BlockName            string            `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string            `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	ReleaseId            string            `protobuf:"bytes,3,opt,name=releaseId,proto3" json:"releaseId,omitempty"`
	State                BlockStatus_State `protobuf:"varint,7,opt,name=state,proto3,enum=BlockStatus_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlockStatus) Reset()         { *m = BlockStatus{} }
func (m *BlockStatus) String() string { return proto.CompactTextString(m) }
func (*BlockStatus) ProtoMessage()    {}
func (*BlockStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{15}
}

func (m *BlockStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStatus.Unmarshal(m, b)
}
func (m *BlockStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStatus.Marshal(b, m, deterministic)
}
func (m *BlockStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStatus.Merge(m, src)
}
func (m *BlockStatus) XXX_Size() int {
	return xxx_messageInfo_BlockStatus.Size(m)
}
func (m *BlockStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStatus proto.InternalMessageInfo

func (m *BlockStatus) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *BlockStatus) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *BlockStatus) GetReleaseId() string {
	if m != nil {
		return m.ReleaseId
	}
	return ""
}

func (m *BlockStatus) GetState() BlockStatus_State {
	if m != nil {
		return m.State
	}
	return BlockStatus_NOT_SET
}

type BlockStatuses struct {
	BlockStatuses        []*BlockStatus `protobuf:"bytes,1,rep,name=blockStatuses,proto3" json:"blockStatuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockStatuses) Reset()         { *m = BlockStatuses{} }
func (m *BlockStatuses) String() string { return proto.CompactTextString(m) }
func (*BlockStatuses) ProtoMessage()    {}
func (*BlockStatuses) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{16}
}

func (m *BlockStatuses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStatuses.Unmarshal(m, b)
}
func (m *BlockStatuses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStatuses.Marshal(b, m, deterministic)
}
func (m *BlockStatuses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStatuses.Merge(m, src)
}
func (m *BlockStatuses) XXX_Size() int {
	return xxx_messageInfo_BlockStatuses.Size(m)
}
func (m *BlockStatuses) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStatuses.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStatuses proto.InternalMessageInfo

func (m *BlockStatuses) GetBlockStatuses() []*BlockStatus {
	if m != nil {
		return m.BlockStatuses
	}
	return nil
}

type BlockMetrics struct {
	BlockName            string                    `protobuf:"bytes,1,opt,name=blockName,proto3" json:"blockName,omitempty"`
	EnvId                string                    `protobuf:"bytes,2,opt,name=envId,proto3" json:"envId,omitempty"`
	Instances            map[string]*BlockInstance `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Storages             map[string]*BlockStorage  `protobuf:"bytes,5,rep,name=storages,proto3" json:"storages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BlockMetrics) Reset()         { *m = BlockMetrics{} }
func (m *BlockMetrics) String() string { return proto.CompactTextString(m) }
func (*BlockMetrics) ProtoMessage()    {}
func (*BlockMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{17}
}

func (m *BlockMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetrics.Unmarshal(m, b)
}
func (m *BlockMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetrics.Marshal(b, m, deterministic)
}
func (m *BlockMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetrics.Merge(m, src)
}
func (m *BlockMetrics) XXX_Size() int {
	return xxx_messageInfo_BlockMetrics.Size(m)
}
func (m *BlockMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetrics proto.InternalMessageInfo

func (m *BlockMetrics) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *BlockMetrics) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *BlockMetrics) GetInstances() map[string]*BlockInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *BlockMetrics) GetStorages() map[string]*BlockStorage {
	if m != nil {
		return m.Storages
	}
	return nil
}

type BlockInstance struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseId            string              `protobuf:"bytes,2,opt,name=releaseId,proto3" json:"releaseId,omitempty"`
	CpuRequests          int64               `protobuf:"varint,3,opt,name=cpuRequests,proto3" json:"cpuRequests,omitempty"`
	CpuUsage             int64               `protobuf:"varint,4,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemRequests          int64               `protobuf:"varint,5,opt,name=memRequests,proto3" json:"memRequests,omitempty"`
	MemUsage             int64               `protobuf:"varint,6,opt,name=memUsage,proto3" json:"memUsage,omitempty"`
	Restarts             int32               `protobuf:"varint,7,opt,name=restarts,proto3" json:"restarts,omitempty"`
	State                BlockInstance_State `protobuf:"varint,8,opt,name=state,proto3,enum=BlockInstance_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlockInstance) Reset()         { *m = BlockInstance{} }
func (m *BlockInstance) String() string { return proto.CompactTextString(m) }
func (*BlockInstance) ProtoMessage()    {}
func (*BlockInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{18}
}

func (m *BlockInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInstance.Unmarshal(m, b)
}
func (m *BlockInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInstance.Marshal(b, m, deterministic)
}
func (m *BlockInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInstance.Merge(m, src)
}
func (m *BlockInstance) XXX_Size() int {
	return xxx_messageInfo_BlockInstance.Size(m)
}
func (m *BlockInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInstance.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInstance proto.InternalMessageInfo

func (m *BlockInstance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlockInstance) GetReleaseId() string {
	if m != nil {
		return m.ReleaseId
	}
	return ""
}

func (m *BlockInstance) GetCpuRequests() int64 {
	if m != nil {
		return m.CpuRequests
	}
	return 0
}

func (m *BlockInstance) GetCpuUsage() int64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *BlockInstance) GetMemRequests() int64 {
	if m != nil {
		return m.MemRequests
	}
	return 0
}

func (m *BlockInstance) GetMemUsage() int64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *BlockInstance) GetRestarts() int32 {
	if m != nil {
		return m.Restarts
	}
	return 0
}

func (m *BlockInstance) GetState() BlockInstance_State {
	if m != nil {
		return m.State
	}
	return BlockInstance_NOT_SET
}

// the main difference between mountedCapacityInBytes and capacityInBytes is
// capacityInBytes will return a neat figure (coz it is the k8s PVC request)
// while mountedCapacityInBytes will be in bytes format at os level (so it will never be 1GB but sth like 0.98 GB)
type BlockStorage struct {
	Name                   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CapacityInBytes        int64    `protobuf:"varint,2,opt,name=capacityInBytes,proto3" json:"capacityInBytes,omitempty"`
	UsagePercent           string   `protobuf:"bytes,3,opt,name=usagePercent,proto3" json:"usagePercent,omitempty"`
	MountPath              string   `protobuf:"bytes,4,opt,name=mountPath,proto3" json:"mountPath,omitempty"`
	InstanceId             string   `protobuf:"bytes,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	MountedUsageInBytes    int64    `protobuf:"varint,6,opt,name=mountedUsageInBytes,proto3" json:"mountedUsageInBytes,omitempty"`
	MountedCapacityInBytes int64    `protobuf:"varint,7,opt,name=mountedCapacityInBytes,proto3" json:"mountedCapacityInBytes,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BlockStorage) Reset()         { *m = BlockStorage{} }
func (m *BlockStorage) String() string { return proto.CompactTextString(m) }
func (*BlockStorage) ProtoMessage()    {}
func (*BlockStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{19}
}

func (m *BlockStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStorage.Unmarshal(m, b)
}
func (m *BlockStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStorage.Marshal(b, m, deterministic)
}
func (m *BlockStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStorage.Merge(m, src)
}
func (m *BlockStorage) XXX_Size() int {
	return xxx_messageInfo_BlockStorage.Size(m)
}
func (m *BlockStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStorage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStorage proto.InternalMessageInfo

func (m *BlockStorage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlockStorage) GetCapacityInBytes() int64 {
	if m != nil {
		return m.CapacityInBytes
	}
	return 0
}

func (m *BlockStorage) GetUsagePercent() string {
	if m != nil {
		return m.UsagePercent
	}
	return ""
}

func (m *BlockStorage) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

func (m *BlockStorage) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *BlockStorage) GetMountedUsageInBytes() int64 {
	if m != nil {
		return m.MountedUsageInBytes
	}
	return 0
}

func (m *BlockStorage) GetMountedCapacityInBytes() int64 {
	if m != nil {
		return m.MountedCapacityInBytes
	}
	return 0
}

type BlocksMetrics struct {
	Blocks               map[string]*BlockMetrics `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BlocksMetrics) Reset()         { *m = BlocksMetrics{} }
func (m *BlocksMetrics) String() string { return proto.CompactTextString(m) }
func (*BlocksMetrics) ProtoMessage()    {}
func (*BlocksMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{20}
}

func (m *BlocksMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksMetrics.Unmarshal(m, b)
}
func (m *BlocksMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksMetrics.Marshal(b, m, deterministic)
}
func (m *BlocksMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksMetrics.Merge(m, src)
}
func (m *BlocksMetrics) XXX_Size() int {
	return xxx_messageInfo_BlocksMetrics.Size(m)
}
func (m *BlocksMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksMetrics proto.InternalMessageInfo

func (m *BlocksMetrics) GetBlocks() map[string]*BlockMetrics {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Language struct {
	Language             BuildConfig_Language `protobuf:"varint,1,opt,name=language,proto3,enum=BuildConfig_Language" json:"language,omitempty"`
	Image                string               `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	VersionsTags         map[string]string    `protobuf:"bytes,3,rep,name=versionsTags,proto3" json:"versionsTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{21}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetLanguage() BuildConfig_Language {
	if m != nil {
		return m.Language
	}
	return BuildConfig_NOT_SET
}

func (m *Language) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Language) GetVersionsTags() map[string]string {
	if m != nil {
		return m.VersionsTags
	}
	return nil
}

type MemoryOptions struct {
	DefaultValue         int32    `protobuf:"varint,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryOptions) Reset()         { *m = MemoryOptions{} }
func (m *MemoryOptions) String() string { return proto.CompactTextString(m) }
func (*MemoryOptions) ProtoMessage()    {}
func (*MemoryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{22}
}

func (m *MemoryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryOptions.Unmarshal(m, b)
}
func (m *MemoryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryOptions.Marshal(b, m, deterministic)
}
func (m *MemoryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryOptions.Merge(m, src)
}
func (m *MemoryOptions) XXX_Size() int {
	return xxx_messageInfo_MemoryOptions.Size(m)
}
func (m *MemoryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryOptions proto.InternalMessageInfo

func (m *MemoryOptions) GetDefaultValue() int32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *MemoryOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type CPUOptions struct {
	DefaultValue         float32   `protobuf:"fixed32,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []float32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CPUOptions) Reset()         { *m = CPUOptions{} }
func (m *CPUOptions) String() string { return proto.CompactTextString(m) }
func (*CPUOptions) ProtoMessage()    {}
func (*CPUOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{23}
}

func (m *CPUOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUOptions.Unmarshal(m, b)
}
func (m *CPUOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUOptions.Marshal(b, m, deterministic)
}
func (m *CPUOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUOptions.Merge(m, src)
}
func (m *CPUOptions) XXX_Size() int {
	return xxx_messageInfo_CPUOptions.Size(m)
}
func (m *CPUOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CPUOptions proto.InternalMessageInfo

func (m *CPUOptions) GetDefaultValue() float32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *CPUOptions) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type TimeoutOptions struct {
	DefaultValue         int32    `protobuf:"varint,1,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeoutOptions) Reset()         { *m = TimeoutOptions{} }
func (m *TimeoutOptions) String() string { return proto.CompactTextString(m) }
func (*TimeoutOptions) ProtoMessage()    {}
func (*TimeoutOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{24}
}

func (m *TimeoutOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutOptions.Unmarshal(m, b)
}
func (m *TimeoutOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutOptions.Marshal(b, m, deterministic)
}
func (m *TimeoutOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutOptions.Merge(m, src)
}
func (m *TimeoutOptions) XXX_Size() int {
	return xxx_messageInfo_TimeoutOptions.Size(m)
}
func (m *TimeoutOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutOptions proto.InternalMessageInfo

func (m *TimeoutOptions) GetDefaultValue() int32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *TimeoutOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type AutoScalingOptions struct {
	DefaultMinValue      int32    `protobuf:"varint,1,opt,name=defaultMinValue,proto3" json:"defaultMinValue,omitempty"`
	DefaultMaxValue      int32    `protobuf:"varint,2,opt,name=defaultMaxValue,proto3" json:"defaultMaxValue,omitempty"`
	Values               []int32  `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoScalingOptions) Reset()         { *m = AutoScalingOptions{} }
func (m *AutoScalingOptions) String() string { return proto.CompactTextString(m) }
func (*AutoScalingOptions) ProtoMessage()    {}
func (*AutoScalingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{25}
}

func (m *AutoScalingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoScalingOptions.Unmarshal(m, b)
}
func (m *AutoScalingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoScalingOptions.Marshal(b, m, deterministic)
}
func (m *AutoScalingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoScalingOptions.Merge(m, src)
}
func (m *AutoScalingOptions) XXX_Size() int {
	return xxx_messageInfo_AutoScalingOptions.Size(m)
}
func (m *AutoScalingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoScalingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoScalingOptions proto.InternalMessageInfo

func (m *AutoScalingOptions) GetDefaultMinValue() int32 {
	if m != nil {
		return m.DefaultMinValue
	}
	return 0
}

func (m *AutoScalingOptions) GetDefaultMaxValue() int32 {
	if m != nil {
		return m.DefaultMaxValue
	}
	return 0
}

func (m *AutoScalingOptions) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type KintoConfiguration struct {
	Languages            []*Language         `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	MemoryOptions        *MemoryOptions      `protobuf:"bytes,2,opt,name=memoryOptions,proto3" json:"memoryOptions,omitempty"`
	CpuOptions           *CPUOptions         `protobuf:"bytes,3,opt,name=cpuOptions,proto3" json:"cpuOptions,omitempty"`
	TimeoutOptions       *TimeoutOptions     `protobuf:"bytes,4,opt,name=timeoutOptions,proto3" json:"timeoutOptions,omitempty"`
	AutoScalingOptions   *AutoScalingOptions `protobuf:"bytes,5,opt,name=autoScalingOptions,proto3" json:"autoScalingOptions,omitempty"`
	JobTimeoutOptions    *TimeoutOptions     `protobuf:"bytes,6,opt,name=jobTimeoutOptions,proto3" json:"jobTimeoutOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *KintoConfiguration) Reset()         { *m = KintoConfiguration{} }
func (m *KintoConfiguration) String() string { return proto.CompactTextString(m) }
func (*KintoConfiguration) ProtoMessage()    {}
func (*KintoConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{26}
}

func (m *KintoConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KintoConfiguration.Unmarshal(m, b)
}
func (m *KintoConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KintoConfiguration.Marshal(b, m, deterministic)
}
func (m *KintoConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KintoConfiguration.Merge(m, src)
}
func (m *KintoConfiguration) XXX_Size() int {
	return xxx_messageInfo_KintoConfiguration.Size(m)
}
func (m *KintoConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_KintoConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_KintoConfiguration proto.InternalMessageInfo

func (m *KintoConfiguration) GetLanguages() []*Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *KintoConfiguration) GetMemoryOptions() *MemoryOptions {
	if m != nil {
		return m.MemoryOptions
	}
	return nil
}

func (m *KintoConfiguration) GetCpuOptions() *CPUOptions {
	if m != nil {
		return m.CpuOptions
	}
	return nil
}

func (m *KintoConfiguration) GetTimeoutOptions() *TimeoutOptions {
	if m != nil {
		return m.TimeoutOptions
	}
	return nil
}

func (m *KintoConfiguration) GetAutoScalingOptions() *AutoScalingOptions {
	if m != nil {
		return m.AutoScalingOptions
	}
	return nil
}

func (m *KintoConfiguration) GetJobTimeoutOptions() *TimeoutOptions {
	if m != nil {
		return m.JobTimeoutOptions
	}
	return nil
}

type Logs struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logs) Reset()         { *m = Logs{} }
func (m *Logs) String() string { return proto.CompactTextString(m) }
func (*Logs) ProtoMessage()    {}
func (*Logs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{27}
}

func (m *Logs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logs.Unmarshal(m, b)
}
func (m *Logs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logs.Marshal(b, m, deterministic)
}
func (m *Logs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logs.Merge(m, src)
}
func (m *Logs) XXX_Size() int {
	return xxx_messageInfo_Logs.Size(m)
}
func (m *Logs) XXX_DiscardUnknown() {
	xxx_messageInfo_Logs.DiscardUnknown(m)
}

var xxx_messageInfo_Logs proto.InternalMessageInfo

func (m *Logs) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type JobStatus struct {
	InstanceName         string          `protobuf:"bytes,1,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	State                JobStatus_State `protobuf:"varint,2,opt,name=state,proto3,enum=JobStatus_State" json:"state,omitempty"`
	StartTimestamp       int64           `protobuf:"varint,3,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp         int64           `protobuf:"varint,4,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{28}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *JobStatus) GetState() JobStatus_State {
	if m != nil {
		return m.State
	}
	return JobStatus_NOT_SET
}

func (m *JobStatus) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *JobStatus) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type TeleportServiceData struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Credentials          string   `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeleportServiceData) Reset()         { *m = TeleportServiceData{} }
func (m *TeleportServiceData) String() string { return proto.CompactTextString(m) }
func (*TeleportServiceData) ProtoMessage()    {}
func (*TeleportServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{29}
}

func (m *TeleportServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleportServiceData.Unmarshal(m, b)
}
func (m *TeleportServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleportServiceData.Marshal(b, m, deterministic)
}
func (m *TeleportServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleportServiceData.Merge(m, src)
}
func (m *TeleportServiceData) XXX_Size() int {
	return xxx_messageInfo_TeleportServiceData.Size(m)
}
func (m *TeleportServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleportServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_TeleportServiceData proto.InternalMessageInfo

func (m *TeleportServiceData) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TeleportServiceData) GetCredentials() string {
	if m != nil {
		return m.Credentials
	}
	return ""
}

type ReleaseConfig struct {
	BuildConfig          *BuildConfig `protobuf:"bytes,1,opt,name=buildConfig,proto3" json:"buildConfig,omitempty"`
	RunConfig            *RunConfig   `protobuf:"bytes,2,opt,name=runConfig,proto3" json:"runConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReleaseConfig) Reset()         { *m = ReleaseConfig{} }
func (m *ReleaseConfig) String() string { return proto.CompactTextString(m) }
func (*ReleaseConfig) ProtoMessage()    {}
func (*ReleaseConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{30}
}

func (m *ReleaseConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseConfig.Unmarshal(m, b)
}
func (m *ReleaseConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseConfig.Marshal(b, m, deterministic)
}
func (m *ReleaseConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseConfig.Merge(m, src)
}
func (m *ReleaseConfig) XXX_Size() int {
	return xxx_messageInfo_ReleaseConfig.Size(m)
}
func (m *ReleaseConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseConfig proto.InternalMessageInfo

func (m *ReleaseConfig) GetBuildConfig() *BuildConfig {
	if m != nil {
		return m.BuildConfig
	}
	return nil
}

func (m *ReleaseConfig) GetRunConfig() *RunConfig {
	if m != nil {
		return m.RunConfig
	}
	return nil
}

func init() {
	proto.RegisterEnum("Block_Type", Block_Type_name, Block_Type_value)
	proto.RegisterEnum("Release_Type", Release_Type_name, Release_Type_value)
	proto.RegisterEnum("BuildConfig_Language", BuildConfig_Language_name, BuildConfig_Language_value)
	proto.RegisterEnum("RunConfig_Protocol", RunConfig_Protocol_name, RunConfig_Protocol_value)
	proto.RegisterEnum("Status_State", Status_State_name, Status_State_value)
	proto.RegisterEnum("BuildStatus_State", BuildStatus_State_name, BuildStatus_State_value)
	proto.RegisterEnum("BlockStatus_State", BlockStatus_State_name, BlockStatus_State_value)
	proto.RegisterEnum("BlockInstance_State", BlockInstance_State_name, BlockInstance_State_value)
	proto.RegisterEnum("JobStatus_State", JobStatus_State_name, JobStatus_State_value)
	proto.RegisterType((*Environment)(nil), "Environment")
	proto.RegisterType((*Environments)(nil), "Environments")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterMapType((map[string]*Release)(nil), "Block.ReleasesEntry")
	proto.RegisterType((*Blocks)(nil), "Blocks")
	proto.RegisterType((*Release)(nil), "Release")
	proto.RegisterType((*BuildConfig)(nil), "BuildConfig")
	proto.RegisterMapType((map[string]string)(nil), "BuildConfig.BuildArgsEntry")
	proto.RegisterType((*RunConfig)(nil), "RunConfig")
	proto.RegisterMapType((map[string]string)(nil), "RunConfig.EnvVarsEntry")
	proto.RegisterType((*Repository)(nil), "Repository")
	proto.RegisterType((*JobSpec)(nil), "JobSpec")
	proto.RegisterType((*AutoScaling)(nil), "AutoScaling")
	proto.RegisterType((*Resources)(nil), "Resources")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*ReleasesStatus)(nil), "ReleasesStatus")
	proto.RegisterMapType((map[string]*Status)(nil), "ReleasesStatus.ReleasesEntry")
	proto.RegisterType((*BuildStatus)(nil), "BuildStatus")
	proto.RegisterType((*ConsoleLog)(nil), "ConsoleLog")
	proto.RegisterType((*BlockStatus)(nil), "BlockStatus")
	proto.RegisterType((*BlockStatuses)(nil), "BlockStatuses")
	proto.RegisterType((*BlockMetrics)(nil), "BlockMetrics")
	proto.RegisterMapType((map[string]*BlockInstance)(nil), "BlockMetrics.InstancesEntry")
	proto.RegisterMapType((map[string]*BlockStorage)(nil), "BlockMetrics.StoragesEntry")
	proto.RegisterType((*BlockInstance)(nil), "BlockInstance")
	proto.RegisterType((*BlockStorage)(nil), "BlockStorage")
	proto.RegisterType((*BlocksMetrics)(nil), "BlocksMetrics")
	proto.RegisterMapType((map[string]*BlockMetrics)(nil), "BlocksMetrics.BlocksEntry")
	proto.RegisterType((*Language)(nil), "Language")
	proto.RegisterMapType((map[string]string)(nil), "Language.VersionsTagsEntry")
	proto.RegisterType((*MemoryOptions)(nil), "MemoryOptions")
	proto.RegisterType((*CPUOptions)(nil), "CPUOptions")
	proto.RegisterType((*TimeoutOptions)(nil), "TimeoutOptions")
	proto.RegisterType((*AutoScalingOptions)(nil), "AutoScalingOptions")
	proto.RegisterType((*KintoConfiguration)(nil), "KintoConfiguration")
	proto.RegisterType((*Logs)(nil), "Logs")
	proto.RegisterType((*JobStatus)(nil), "JobStatus")
	proto.RegisterType((*TeleportServiceData)(nil), "TeleportServiceData")
	proto.RegisterType((*ReleaseConfig)(nil), "ReleaseConfig")
}

func init() {
	proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573)
}

var fileDescriptor_0b5431a010549573 = []byte{
	// 2467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5b, 0x6f, 0xe3, 0xc6,
	0x15, 0x2e, 0x75, 0xe7, 0x91, 0xa5, 0xe5, 0xce, 0xba, 0x89, 0xa0, 0x6c, 0x92, 0x2d, 0x13, 0x6c,
	0xdd, 0x2c, 0x4a, 0x67, 0xdd, 0x20, 0xd9, 0x2c, 0x5a, 0x04, 0xba, 0x70, 0xd7, 0xb2, 0x65, 0x49,
	0x19, 0x51, 0xde, 0x6c, 0x5f, 0x0c, 0x9a, 0x9a, 0xb5, 0xb9, 0x16, 0x49, 0x95, 0x17, 0x23, 0xee,
	0x43, 0xd1, 0xb7, 0x02, 0x01, 0xfa, 0x50, 0xa0, 0x0f, 0xfd, 0x2d, 0x7d, 0xeb, 0x43, 0x7f, 0x40,
	0x0b, 0x14, 0x28, 0x50, 0xe4, 0x8f, 0xf4, 0xa9, 0x98, 0x0b, 0xa9, 0xa1, 0x25, 0xef, 0xa5, 0xed,
	0x93, 0x66, 0xbe, 0x73, 0xce, 0xcc, 0xf0, 0x9c, 0x6f, 0xce, 0x39, 0x23, 0xd8, 0xf2, 0x82, 0x39,
	0x59, 0x44, 0xc6, 0x32, 0x0c, 0xe2, 0xa0, 0xfd, 0xe1, 0x59, 0x10, 0x9c, 0x2d, 0xc8, 0x2e, 0x9b,
	0x9d, 0x26, 0x2f, 0x76, 0x63, 0xd7, 0x23, 0x51, 0x6c, 0x7b, 0x4b, 0xae, 0xa0, 0x3f, 0x84, 0xba,
	0xe9, 0x5f, 0xba, 0x61, 0xe0, 0x7b, 0xc4, 0x8f, 0x51, 0x13, 0x0a, 0xee, 0xbc, 0xa5, 0xdc, 0x53,
	0x76, 0x54, 0x5c, 0x70, 0xe7, 0x08, 0x41, 0xc9, 0xb7, 0x3d, 0xd2, 0x2a, 0x30, 0x84, 0x8d, 0xf5,
	0x3d, 0xd8, 0x92, 0x4c, 0x22, 0xa4, 0x43, 0xd9, 0x8d, 0x89, 0x17, 0xb5, 0x94, 0x7b, 0xc5, 0x9d,
	0xfa, 0xde, 0x96, 0x21, 0x49, 0x31, 0x17, 0xe9, 0xbf, 0x2b, 0x41, 0xb9, 0xbb, 0x08, 0x9c, 0x8b,
	0x37, 0xd9, 0x01, 0x6d, 0x43, 0x99, 0xf8, 0x97, 0x83, 0x79, 0xab, 0xc8, 0x40, 0x3e, 0x41, 0xf7,
	0xa0, 0x3e, 0x77, 0xa3, 0xe5, 0xc2, 0xbe, 0x1a, 0x51, 0x83, 0x12, 0x93, 0xc9, 0x10, 0xfa, 0x14,
	0x6a, 0x21, 0x59, 0x10, 0x3b, 0x22, 0x51, 0xab, 0xcc, 0x0e, 0xb3, 0x6d, 0xb0, 0x5d, 0x0d, 0x2c,
	0x60, 0xd3, 0x8f, 0xc3, 0x2b, 0x9c, 0x69, 0xa1, 0x8f, 0xa1, 0xe1, 0x24, 0x51, 0x1c, 0x78, 0xfd,
	0xc0, 0xb3, 0x5d, 0x3f, 0x6a, 0x55, 0xee, 0x15, 0x77, 0x54, 0x9c, 0x07, 0xe9, 0xce, 0x6e, 0x34,
	0x49, 0x4e, 0x17, 0xae, 0x33, 0xc3, 0xc3, 0x56, 0xf5, 0x9e, 0xb2, 0x53, 0xc3, 0x32, 0x84, 0x76,
	0xe0, 0xd6, 0xd2, 0x0e, 0x89, 0x1f, 0xb3, 0xed, 0xd8, 0xf9, 0x6a, 0xec, 0x7c, 0xd7, 0x61, 0xf4,
	0x09, 0x68, 0x12, 0x64, 0xb2, 0xcf, 0x54, 0x99, 0xea, 0x1a, 0xde, 0x36, 0xa1, 0x91, 0x3b, 0x38,
	0xd2, 0xa0, 0x78, 0x41, 0xae, 0x84, 0xf7, 0xe8, 0x10, 0x7d, 0x00, 0xe5, 0x4b, 0x7b, 0x91, 0x70,
	0xff, 0xd5, 0xf7, 0x6a, 0xe9, 0x97, 0x62, 0x0e, 0x3f, 0x2e, 0x3c, 0x52, 0xf4, 0xef, 0x14, 0x28,
	0x59, 0x57, 0x4b, 0x82, 0xea, 0x50, 0x1d, 0x8d, 0xad, 0x93, 0xa9, 0x69, 0x69, 0x3f, 0x40, 0xb7,
	0xa0, 0xde, 0xed, 0xf4, 0x0e, 0xcd, 0x51, 0xff, 0xa4, 0x33, 0x19, 0x68, 0x0a, 0x05, 0xa6, 0x56,
	0xc7, 0x1a, 0xf4, 0x4e, 0xa6, 0x03, 0xcb, 0xd4, 0x0a, 0x54, 0xfd, 0x99, 0xd9, 0x3d, 0xe9, 0x4c,
	0x26, 0x5a, 0x11, 0x6d, 0x41, 0xed, 0xa0, 0x73, 0x34, 0xb5, 0x3a, 0xbd, 0x43, 0xad, 0x84, 0xaa,
	0x50, 0x3c, 0x18, 0x77, 0xb5, 0x32, 0x85, 0x7b, 0x78, 0x3c, 0x3a, 0xa1, 0xb3, 0x0a, 0x02, 0xa8,
	0x3c, 0x1b, 0xe3, 0x43, 0x13, 0x6b, 0x55, 0x6a, 0xdd, 0xeb, 0x58, 0x9d, 0xe1, 0xf8, 0xa9, 0x56,
	0x43, 0x35, 0x28, 0xed, 0x9b, 0xc3, 0x23, 0x4d, 0xd5, 0xef, 0x43, 0x85, 0x7d, 0x61, 0x84, 0xee,
	0xe6, 0x79, 0x53, 0xe1, 0xa1, 0x4a, 0x19, 0xf3, 0x7d, 0x11, 0xaa, 0xe2, 0x5b, 0xd6, 0x38, 0xf3,
	0x08, 0x54, 0x27, 0x24, 0x76, 0x4c, 0xe6, 0x9d, 0x58, 0x7c, 0x78, 0xdb, 0xe0, 0x4c, 0x37, 0x52,
	0xa6, 0x1b, 0x56, 0xca, 0x74, 0xbc, 0x52, 0x46, 0x06, 0xd4, 0x4f, 0x13, 0x77, 0x31, 0xef, 0x05,
	0xfe, 0x0b, 0xf7, 0x8c, 0xf1, 0x8b, 0x32, 0xb6, 0xbb, 0xc2, 0xb0, 0xac, 0x80, 0x76, 0x40, 0x0d,
	0x13, 0x5f, 0x68, 0x97, 0x98, 0x36, 0x18, 0x38, 0x45, 0xf0, 0x4a, 0x88, 0x3e, 0x84, 0x4a, 0x14,
	0xdb, 0x71, 0x42, 0x99, 0x47, 0xd5, 0xaa, 0xc6, 0x94, 0x4d, 0xb1, 0x80, 0xe9, 0xa1, 0xa3, 0xd8,
	0x0e, 0xf9, 0xa1, 0x2b, 0xaf, 0x3f, 0x74, 0xa6, 0x8c, 0x3e, 0x83, 0x2a, 0xf1, 0xe7, 0xcc, 0xae,
	0xfa, 0x5a, 0xbb, 0x54, 0x15, 0xfd, 0x08, 0x4a, 0xf1, 0xd5, 0x92, 0xf3, 0xb0, 0xb9, 0xd7, 0x48,
	0x89, 0x61, 0x50, 0x26, 0x60, 0x26, 0xa2, 0x77, 0x2f, 0xb6, 0xcf, 0xa2, 0x96, 0xca, 0x48, 0xcf,
	0xc6, 0xe8, 0x2e, 0xa8, 0x4e, 0xe0, 0x79, 0x6e, 0x3c, 0x3d, 0xb7, 0x5b, 0xc0, 0x5c, 0xbe, 0x02,
	0xf4, 0xfd, 0x4d, 0x4c, 0x02, 0xa8, 0xf4, 0xcd, 0xc9, 0x70, 0xfc, 0x5c, 0x53, 0x28, 0x1f, 0x66,
	0x23, 0x31, 0x63, 0x0c, 0x9a, 0xce, 0xa6, 0x13, 0x73, 0xd4, 0xe7, 0x0c, 0xc2, 0xe3, 0xe1, 0xb0,
	0xcb, 0x18, 0xa4, 0xff, 0xbb, 0x04, 0x75, 0xc9, 0xed, 0x6b, 0x31, 0xde, 0x86, 0xb2, 0xeb, 0xd9,
	0x67, 0x69, 0x62, 0xe0, 0x13, 0xf4, 0x10, 0x6a, 0x0b, 0xdb, 0x3f, 0x4b, 0xa8, 0xa0, 0xc8, 0x3e,
	0xec, 0x87, 0x72, 0xf0, 0x8c, 0xa1, 0x10, 0xe2, 0x4c, 0x8d, 0x5e, 0xcd, 0x74, 0x7c, 0x4c, 0xc2,
	0xc8, 0x0d, 0x7c, 0x91, 0x3a, 0xae, 0xc3, 0x48, 0x87, 0x2d, 0x11, 0x7b, 0xcf, 0xb3, 0xfd, 0x39,
	0x0b, 0xa4, 0x8a, 0x73, 0x18, 0xfa, 0x00, 0x80, 0xc5, 0x9c, 0x6b, 0x54, 0x98, 0x86, 0x84, 0x50,
	0xf9, 0xd2, 0x8e, 0xcf, 0xad, 0xa0, 0x17, 0xcc, 0x09, 0x0b, 0x97, 0x8a, 0x25, 0x04, 0x19, 0x80,
	0xf8, 0x8c, 0xb2, 0xc3, 0x75, 0xc6, 0x49, 0xbc, 0x4c, 0xe2, 0x56, 0x9d, 0xe9, 0x6d, 0x90, 0x50,
	0xfd, 0x79, 0xe0, 0x5c, 0x90, 0xf0, 0x85, 0xbb, 0x20, 0x4f, 0xdc, 0x05, 0x91, 0x72, 0xcb, 0x06,
	0x09, 0xfa, 0x12, 0x54, 0x76, 0xde, 0x4e, 0x28, 0xe2, 0x5a, 0xdf, 0x7b, 0x2f, 0xe7, 0xa1, 0x6e,
	0x2a, 0xe5, 0xa9, 0x70, 0xa5, 0x8d, 0x1e, 0x00, 0x84, 0x64, 0x19, 0x44, 0x6e, 0x1c, 0x84, 0x57,
	0x2c, 0xf4, 0xf5, 0xbd, 0xba, 0x81, 0x33, 0x08, 0x4b, 0xe2, 0xf6, 0xcf, 0xa1, 0x99, 0x5f, 0x69,
	0x43, 0x6e, 0xda, 0x96, 0x73, 0x93, 0x2a, 0x67, 0xa4, 0xdf, 0x40, 0x2d, 0x8d, 0x54, 0x9e, 0x4a,
	0x4d, 0x80, 0xfe, 0xb8, 0x77, 0x68, 0xe2, 0x27, 0x83, 0xa1, 0xa9, 0x29, 0x94, 0x5a, 0x4f, 0xc7,
	0xc3, 0xce, 0xe8, 0xa9, 0x56, 0xa0, 0xe3, 0xd1, 0xb8, 0x6f, 0x1e, 0x4c, 0xb5, 0x22, 0x1d, 0x4f,
	0x9e, 0x5b, 0xfb, 0xe3, 0x91, 0x56, 0xa2, 0xb9, 0xe5, 0xa0, 0x73, 0xdc, 0xd1, 0xca, 0x74, 0x84,
	0x67, 0xdd, 0xe7, 0x5a, 0x85, 0xe6, 0xa7, 0xc9, 0xfe, 0x44, 0xab, 0x72, 0x68, 0x6a, 0x69, 0x35,
	0x6a, 0x62, 0x0e, 0x07, 0xdf, 0x0c, 0xb0, 0xa6, 0xea, 0xff, 0x2a, 0x81, 0x8a, 0xa5, 0xab, 0xcb,
	0x6f, 0x8a, 0xc2, 0x08, 0x55, 0x17, 0x25, 0x23, 0x7f, 0x4f, 0x96, 0x41, 0x18, 0xa7, 0x35, 0x8a,
	0x8e, 0x69, 0x26, 0xb1, 0x93, 0x38, 0x98, 0x3a, 0xf6, 0xc2, 0xf5, 0x57, 0x99, 0xa4, 0xb3, 0xc2,
	0xb0, 0xac, 0x80, 0x1e, 0xd2, 0x4b, 0x7c, 0x79, 0x6c, 0x87, 0x51, 0xab, 0xc4, 0xc2, 0xf2, 0xee,
	0x2a, 0x8f, 0xd0, 0x8a, 0x49, 0x25, 0x3c, 0x24, 0xa9, 0x1e, 0x4b, 0x3e, 0x24, 0x0a, 0x92, 0xd0,
	0x21, 0x69, 0x56, 0x01, 0x03, 0xa7, 0x08, 0x5e, 0x09, 0x29, 0x73, 0x69, 0x61, 0x0f, 0x92, 0x78,
	0xe0, 0x4f, 0x89, 0xc3, 0x78, 0x59, 0xc6, 0x39, 0x0c, 0xe9, 0x50, 0x7d, 0x19, 0x9c, 0x4e, 0x97,
	0xc4, 0x11, 0x59, 0xa4, 0x66, 0x1c, 0xf0, 0x39, 0x4e, 0x05, 0xf4, 0x43, 0xcf, 0x83, 0x28, 0x16,
	0xfc, 0x62, 0x63, 0xf4, 0x08, 0xde, 0x75, 0x82, 0x28, 0x1e, 0x2f, 0x63, 0xd7, 0x73, 0x7f, 0x6d,
	0xc7, 0x6e, 0xe0, 0x9b, 0xbe, 0x7d, 0xba, 0x20, 0xbc, 0x6e, 0xd5, 0xf0, 0x4d, 0x62, 0x5a, 0xea,
	0xa2, 0x05, 0x21, 0xcb, 0xa3, 0x60, 0x4e, 0x52, 0x13, 0x60, 0x26, 0x6b, 0x38, 0xda, 0x85, 0x1a,
	0x4b, 0x66, 0x4e, 0xb0, 0x60, 0xb7, 0xa1, 0xb9, 0x77, 0x47, 0xf2, 0xcf, 0x44, 0x88, 0x70, 0xa6,
	0x84, 0x3e, 0x85, 0x3b, 0xd9, 0x22, 0x96, 0x35, 0x9c, 0x12, 0x27, 0xf0, 0xe7, 0x51, 0x6b, 0x8b,
	0x7d, 0xf9, 0x26, 0x51, 0xfb, 0x31, 0xeb, 0x5b, 0x32, 0x3f, 0xbf, 0x15, 0x61, 0x1f, 0x40, 0x2d,
	0x3d, 0x43, 0x9e, 0xb0, 0xb4, 0xb0, 0x59, 0xd6, 0x44, 0x53, 0xe8, 0xe8, 0x29, 0x9e, 0xf4, 0xb4,
	0x82, 0xfe, 0x67, 0x05, 0x60, 0x75, 0x6d, 0xe8, 0x3e, 0x49, 0xb8, 0x48, 0xf7, 0x49, 0xc2, 0x05,
	0xed, 0x27, 0x6c, 0xc7, 0x21, 0x51, 0x64, 0x05, 0x17, 0xc4, 0x17, 0xbb, 0xc9, 0x10, 0x7a, 0x07,
	0x2a, 0xa7, 0xa1, 0xed, 0x3b, 0xe7, 0xa2, 0x05, 0x12, 0x33, 0xf4, 0x39, 0x6c, 0x9f, 0xb9, 0xf1,
	0x79, 0x72, 0x3a, 0xf0, 0xa3, 0xd8, 0x5e, 0x2c, 0x98, 0xbf, 0x07, 0x73, 0x9e, 0xd1, 0xba, 0x85,
	0x96, 0x82, 0x37, 0xca, 0x69, 0x12, 0xe4, 0xf8, 0x2c, 0x22, 0x21, 0xdf, 0x95, 0x67, 0xb7, 0xeb,
	0xb0, 0x3e, 0x86, 0xaa, 0xa0, 0x05, 0x3d, 0xa6, 0x13, 0x06, 0xfe, 0xc4, 0x8e, 0x63, 0x12, 0xfa,
	0xe2, 0x03, 0x64, 0x68, 0x8d, 0x77, 0x85, 0x75, 0xde, 0xe9, 0x5f, 0x43, 0x5d, 0xba, 0x14, 0xd4,
	0x1b, 0x9e, 0xcb, 0x17, 0x2b, 0x63, 0x3a, 0x64, 0x88, 0xfd, 0xad, 0xb0, 0xa5, 0x43, 0x9a, 0x44,
	0x9d, 0x65, 0x32, 0x21, 0xa1, 0x43, 0xfc, 0x98, 0x79, 0xa0, 0x8c, 0x25, 0x44, 0x1f, 0x80, 0x9a,
	0x5d, 0x03, 0xaa, 0xec, 0x11, 0x2f, 0x08, 0xaf, 0x06, 0xfe, 0x51, 0x57, 0xac, 0x2b, 0x21, 0xac,
	0xa0, 0x2d, 0x93, 0x81, 0xdf, 0x0b, 0x42, 0x1e, 0xd8, 0x02, 0x5e, 0x01, 0xfa, 0x1f, 0x15, 0xa8,
	0xf0, 0x42, 0x8d, 0x3e, 0x82, 0x32, 0x2d, 0xd5, 0x5c, 0x89, 0x56, 0x4c, 0x8e, 0xb3, 0x1f, 0x82,
	0xb9, 0x4c, 0x27, 0x50, 0x66, 0xf3, 0x35, 0x16, 0x3c, 0xe9, 0x0c, 0x86, 0x9a, 0xc2, 0x2b, 0x5e,
	0xaf, 0x67, 0x4e, 0xa7, 0xbc, 0xfc, 0xe1, 0xd9, 0x68, 0x34, 0x18, 0x3d, 0xd5, 0x8a, 0x74, 0x42,
	0x0b, 0x21, 0x9d, 0x94, 0xe8, 0xa4, 0xd3, 0x1d, 0x63, 0xcb, 0xec, 0x6b, 0x65, 0x74, 0x1b, 0x1a,
	0xd8, 0x3c, 0x1e, 0x98, 0xcf, 0x4e, 0x44, 0xe1, 0xac, 0xe8, 0x7f, 0x55, 0xa0, 0x99, 0xb6, 0x7e,
	0xe2, 0x78, 0x77, 0x41, 0x3d, 0xcd, 0x9a, 0x4b, 0x1e, 0x8b, 0x15, 0xb0, 0x6a, 0x99, 0x0b, 0x72,
	0xcb, 0xfc, 0xa5, 0xd4, 0x10, 0x17, 0x59, 0xd6, 0x79, 0xdf, 0xc8, 0x2f, 0x7b, 0x53, 0x67, 0xdc,
	0xee, 0xbf, 0xbe, 0xf7, 0x7c, 0x3f, 0xdf, 0x7b, 0x66, 0x1d, 0x8f, 0x74, 0x6f, 0xfe, 0x52, 0x10,
	0x55, 0x5e, 0x7c, 0xc4, 0x4e, 0xea, 0x63, 0x9e, 0x6b, 0x91, 0x21, 0x09, 0x73, 0x8e, 0xce, 0xda,
	0x25, 0xda, 0xd9, 0xbc, 0x49, 0x8f, 0x97, 0x29, 0xa3, 0xc7, 0x00, 0x2f, 0x5c, 0xdf, 0x8d, 0xce,
	0x99, 0x69, 0xf1, 0xb5, 0xa6, 0x92, 0xb6, 0xfe, 0x07, 0x65, 0x63, 0x7c, 0xeb, 0x50, 0x9d, 0x8d,
	0x0e, 0x47, 0xe3, 0x67, 0x23, 0x5e, 0x93, 0xbe, 0x9e, 0x99, 0x33, 0xb3, 0x2f, 0x5a, 0xe4, 0x31,
	0x3e, 0xcc, 0x22, 0x9c, 0xc6, 0x9e, 0x45, 0x98, 0x52, 0x62, 0x86, 0x4d, 0xad, 0x8c, 0x10, 0x34,
	0x07, 0x23, 0xcb, 0xc4, 0xa3, 0xce, 0xf0, 0xc4, 0xc4, 0x78, 0x8c, 0xb5, 0x0a, 0x55, 0xb0, 0x06,
	0x47, 0xe6, 0x78, 0x66, 0x69, 0x55, 0xd4, 0x00, 0xb5, 0xd7, 0x19, 0xf5, 0xcc, 0xe1, 0xd0, 0xec,
	0x6b, 0x35, 0x2a, 0x33, 0xbf, 0x99, 0x0c, 0xb0, 0xd9, 0xd7, 0x54, 0xbd, 0x0f, 0xd0, 0x0b, 0xfc,
	0x28, 0x58, 0x90, 0x61, 0x70, 0x46, 0xaf, 0x9c, 0x4b, 0xef, 0xb6, 0xef, 0x10, 0x89, 0x09, 0x39,
	0x8c, 0xa6, 0xf1, 0xb9, 0x1d, 0xdb, 0xcc, 0x6d, 0x5b, 0x98, 0x8d, 0xf5, 0x7f, 0x2a, 0x50, 0x67,
	0x85, 0xed, 0x7f, 0xa0, 0xd3, 0x5d, 0x5a, 0x90, 0x18, 0x27, 0xb2, 0xb7, 0xd9, 0x0a, 0x58, 0xc5,
	0xb6, 0x9a, 0xc6, 0x76, 0xb5, 0x5d, 0xfe, 0x12, 0x1d, 0xdd, 0xe4, 0xe4, 0x7d, 0xb3, 0x33, 0xb4,
	0xf6, 0x69, 0x1f, 0xd9, 0x00, 0x75, 0x36, 0x4a, 0xa7, 0x05, 0x3a, 0x15, 0x8d, 0xa4, 0x29, 0x5a,
	0xc9, 0xe9, 0xd0, 0x34, 0x27, 0xec, 0x32, 0xe9, 0x3d, 0x68, 0x48, 0x5b, 0x91, 0x08, 0xed, 0x41,
	0xe3, 0x54, 0x06, 0xb2, 0x97, 0xa9, 0xa4, 0x86, 0xf3, 0x2a, 0xfa, 0xdf, 0x0a, 0xb0, 0xc5, 0xc4,
	0x47, 0x24, 0x0e, 0x5d, 0xe7, 0xbf, 0x73, 0xd0, 0x63, 0x50, 0xd3, 0x40, 0xa4, 0x17, 0xee, 0xae,
	0x21, 0xaf, 0x6a, 0x0c, 0x52, 0xb1, 0x68, 0xbf, 0x32, 0x75, 0xf4, 0x05, 0xd4, 0xa2, 0x38, 0x08,
	0xed, 0xb3, 0xec, 0xf1, 0xfa, 0x5e, 0xde, 0x74, 0x2a, 0xa4, 0xe2, 0xa6, 0xa6, 0xca, 0xed, 0x21,
	0x34, 0xf3, 0xab, 0x6e, 0xb8, 0xaa, 0x1f, 0xe7, 0xaf, 0x6a, 0x93, 0xaf, 0x9c, 0x9a, 0x49, 0x37,
	0xb6, 0x7d, 0x00, 0x8d, 0xdc, 0x46, 0x1b, 0x16, 0xfb, 0x28, 0xbf, 0x58, 0x23, 0x75, 0x2b, 0xb3,
	0x92, 0x6f, 0xff, 0xdf, 0x0b, 0x22, 0x32, 0xe9, 0x46, 0xd9, 0x6b, 0x5f, 0x91, 0x5e, 0xfb, 0x39,
	0x56, 0x15, 0xae, 0xb3, 0x8a, 0x16, 0xa1, 0x65, 0x82, 0xc9, 0xaf, 0x12, 0x12, 0xc5, 0x11, 0x63,
	0x5d, 0x11, 0xcb, 0x10, 0x6a, 0x43, 0xcd, 0x59, 0x26, 0xb3, 0x88, 0xbe, 0x09, 0x4a, 0x4c, 0x9c,
	0xcd, 0xa9, 0xb5, 0x47, 0xbc, 0xcc, 0xba, 0xcc, 0xad, 0x25, 0x88, 0x5a, 0x7b, 0xc4, 0xe3, 0xd6,
	0x15, 0x6e, 0x9d, 0xce, 0xa9, 0x2c, 0x24, 0x2c, 0xb1, 0x44, 0x8c, 0xd4, 0x65, 0x9c, 0xcd, 0xd1,
	0x27, 0x29, 0xdb, 0xf9, 0xfb, 0x6a, 0x3b, 0xef, 0xd1, 0x3c, 0xdf, 0x0f, 0x6f, 0xe2, 0x7b, 0x5a,
	0x1d, 0x18, 0xdf, 0x7b, 0xe3, 0xa3, 0xc9, 0xd0, 0xb4, 0x58, 0x5e, 0x51, 0xa1, 0xcc, 0xf3, 0x44,
	0x91, 0xb6, 0xc4, 0xe3, 0xf1, 0xd1, 0xc9, 0xe1, 0x80, 0xe5, 0x86, 0x92, 0xfe, 0xa7, 0x94, 0xa8,
	0xc2, 0xe1, 0x1b, 0x7d, 0xba, 0x03, 0xb7, 0x1c, 0x7b, 0x69, 0x3b, 0x6e, 0x7c, 0x35, 0xf0, 0xbb,
	0x57, 0x31, 0x89, 0x98, 0x67, 0x8b, 0xf8, 0x3a, 0x4c, 0xf3, 0x49, 0x42, 0x3f, 0x56, 0xae, 0xb6,
	0x2a, 0xce, 0x61, 0x34, 0x42, 0x5e, 0x90, 0xf8, 0xf1, 0xc4, 0x8e, 0xcf, 0xc5, 0xe3, 0x69, 0x05,
	0xd0, 0x02, 0x9c, 0xb2, 0x78, 0x90, 0x3e, 0x9a, 0x24, 0x84, 0x76, 0x6a, 0x4c, 0x99, 0xcc, 0x99,
	0x57, 0xd3, 0xf3, 0x70, 0x67, 0x6f, 0x12, 0xa1, 0xcf, 0xe1, 0x1d, 0x01, 0xf7, 0xae, 0x7d, 0x44,
	0x95, 0x19, 0xdd, 0x20, 0xd5, 0x7f, 0xaf, 0x08, 0xbe, 0x45, 0xe9, 0x25, 0xde, 0x83, 0x0a, 0xbb,
	0xb3, 0x69, 0x0a, 0x68, 0x1b, 0x39, 0xb9, 0x98, 0xf1, 0x1b, 0x25, 0x34, 0xdb, 0xfb, 0x22, 0x51,
	0xbe, 0x25, 0xff, 0xc5, 0x92, 0x32, 0xff, 0xff, 0xa1, 0x48, 0xef, 0x1c, 0xf9, 0xe9, 0xaa, 0xbc,
	0xd9, 0xd3, 0x75, 0xf3, 0x1b, 0xf8, 0x2b, 0xd8, 0xba, 0xe4, 0x2f, 0xd6, 0xc8, 0xa2, 0xaf, 0xf7,
	0xa2, 0x48, 0x16, 0xe9, 0x02, 0xc6, 0xb1, 0x24, 0xe5, 0x9f, 0x96, 0x33, 0x68, 0x7f, 0x05, 0xb7,
	0xd7, 0x54, 0xde, 0xaa, 0x1b, 0x3e, 0x84, 0xc6, 0x11, 0x6b, 0xb0, 0x68, 0xd7, 0x1f, 0xf8, 0x8c,
	0x44, 0x73, 0xf2, 0xc2, 0x4e, 0x16, 0xf1, 0x31, 0xb3, 0xe0, 0x5d, 0x58, 0x0e, 0xa3, 0x2d, 0x2d,
	0x5b, 0x81, 0x32, 0xb1, 0xb8, 0x53, 0xc6, 0x62, 0xa6, 0xef, 0x03, 0xf4, 0x26, 0xb3, 0x57, 0xad,
	0x54, 0x78, 0xe5, 0x4a, 0x85, 0x6c, 0xa5, 0x21, 0x34, 0x2d, 0xde, 0x79, 0xfe, 0x3f, 0xce, 0xf5,
	0x5b, 0x05, 0x90, 0xd4, 0xb8, 0xa6, 0x4b, 0xee, 0xc0, 0x2d, 0x61, 0x7e, 0xe4, 0xfa, 0xf2, 0xaa,
	0xd7, 0x61, 0x59, 0xd3, 0xfe, 0xf6, 0x38, 0xf3, 0xa4, 0xa4, 0x29, 0x60, 0xe9, 0x08, 0xc5, 0xdc,
	0x11, 0xbe, 0x2f, 0x00, 0x3a, 0x74, 0xfd, 0x38, 0xe0, 0x14, 0x49, 0x42, 0xd6, 0xce, 0xa3, 0x1f,
	0x83, 0x9a, 0x52, 0x24, 0xe5, 0xb5, 0xba, 0xa2, 0xcf, 0x4a, 0x86, 0x3e, 0x83, 0x86, 0x27, 0xc7,
	0x29, 0xcb, 0xfe, 0xb9, 0xe8, 0xe1, 0xbc, 0x12, 0x7a, 0xc0, 0xba, 0xef, 0xd4, 0xa4, 0x28, 0xfe,
	0x07, 0x58, 0xc5, 0x08, 0x4b, 0x62, 0xf4, 0x05, 0x34, 0xe3, 0x9c, 0xcf, 0xc5, 0xbf, 0x64, 0xb7,
	0x8c, 0x7c, 0x28, 0xf0, 0x35, 0x35, 0xd4, 0x03, 0x64, 0xaf, 0x79, 0x57, 0xbc, 0x72, 0xef, 0x18,
	0xeb, 0x8e, 0xc7, 0x1b, 0xd4, 0xd1, 0x2f, 0xe0, 0xf6, 0xcb, 0xe0, 0x34, 0xbf, 0x93, 0xf8, 0x6f,
	0x6d, 0xed, 0x00, 0xeb, 0x9a, 0x7a, 0x1b, 0x4a, 0xc3, 0xe0, 0x2c, 0xca, 0xfa, 0x25, 0x45, 0xea,
	0x97, 0xbe, 0x2b, 0x80, 0x4a, 0x1f, 0x42, 0xbc, 0x5b, 0x7a, 0x93, 0xae, 0xeb, 0x7e, 0xfe, 0xfd,
	0xa0, 0x19, 0x99, 0x79, 0xbe, 0xb3, 0xbd, 0x0f, 0xcd, 0xac, 0x59, 0x65, 0x1d, 0xa8, 0x28, 0x6a,
	0xd7, 0x50, 0xba, 0x27, 0xf1, 0xe7, 0x2b, 0x2d, 0x5e, 0xdb, 0x72, 0xd8, 0x0d, 0xcf, 0x11, 0xe9,
	0xa9, 0xa1, 0xc8, 0x65, 0xa6, 0x90, 0x2f, 0x33, 0xac, 0x63, 0xed, 0x9b, 0x7c, 0x52, 0x5a, 0xd5,
	0x9c, 0xf2, 0xb5, 0x9a, 0x53, 0xd1, 0x0f, 0xe1, 0x8e, 0x45, 0x16, 0x64, 0x19, 0x84, 0xf1, 0x94,
	0x84, 0x97, 0xae, 0x43, 0xfa, 0x76, 0x6c, 0x67, 0x7f, 0x17, 0x28, 0xd2, 0xdf, 0x05, 0xec, 0xd1,
	0x48, 0xe6, 0xc4, 0x8f, 0x5d, 0x7b, 0x11, 0xa5, 0x6f, 0x5b, 0x09, 0xd2, 0xdd, 0xec, 0x65, 0x21,
	0xfe, 0x7f, 0xb9, 0xf6, 0xa7, 0xac, 0xf2, 0x56, 0x7f, 0xca, 0x16, 0x5e, 0xf1, 0xa7, 0x6c, 0xf7,
	0xc1, 0x2f, 0x7f, 0xc2, 0xdf, 0xb7, 0x86, 0x13, 0x78, 0xbb, 0x17, 0xf4, 0x2a, 0x2d, 0xc3, 0xe0,
	0x25, 0x1f, 0xfd, 0xd4, 0x09, 0x42, 0xb2, 0xbb, 0xbc, 0x38, 0xdb, 0x8d, 0xaf, 0x96, 0x24, 0x3a,
	0xad, 0xb0, 0xb7, 0xc1, 0xcf, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x76, 0xf6, 0xfb, 0x85, 0x42,
	0x19, 0x00, 0x00,
}
