name: Kinto Builder Docker Build And Push

on:
  push:
    branches: [ main ]

jobs:
  kinto-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "TAGS=kintohub/kinto-builder:${GITHUB_SHA},kintohub/kinto-builder:latest" >> $GITHUB_ENV
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: builder/kinto-build/Dockerfile
          push: true
          tags: ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "TAGS=kintohub/kinto-workflow-cli:${GITHUB_SHA},kintohub/kinto-workflow-cli:latest" >> $GITHUB_ENV
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: builder/images/kinto-cli/Dockerfile
          push: true
          tags: ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kinto-workflow-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "TAGS=kintohub/kinto-workflow-main:${GITHUB_SHA},kintohub/kinto-workflow-main:latest" >> $GITHUB_ENV
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: builder/images/Dockerfile
          push: true
          tags:  ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
