name: Kinto Builder Docker Image Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Builder
        uses: kintoproj/kinto-github-actions/tag-docker-image@v1.1
        with:
          from_tag: kintohub/kinto-builder:${{ github.sha }}
          to_tag: kintohub/kinto-builder:${{ env.RELEASE_VERSION }}

      - name: Tag CLI
        uses: kintoproj/kinto-github-actions/tag-docker-image@v1.1
        with:
          from_tag: kintohub/kinto-workflow-cli:${{ github.sha }}
          to_tag: kintohub/kinto-workflow-cli:${{ env.RELEASE_VERSION }}

      - name: Tag Workflow
        uses: kintoproj/kinto-github-actions/tag-docker-image@v1.1
        with:
          from_tag: kintohub/kinto-workflow-main:${{ github.sha }}
          to_tag: kintohub/kinto-workflow-main:${{ env.RELEASE_VERSION }}
