name: Kinto Core Docker Image Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Image
        uses: kintoproj/kinto-github-actions/tag-docker-image@v1.1
        with:
          from_tag: kintohub/kinto-core:${{ github.sha }}
          to_tag: kintohub/kinto-core:${{ env.RELEASE_VERSION }}
