name: Kinto Core Docker Build And Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "TAGS=kintohub/kinto-core:${GITHUB_SHA},kintohub/kinto-core:latest" >> $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./core
          file: ./core/Dockerfile
          push: true
          tags: ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
